In [5]:
import numpy as np

In [1]:
import torch 

Tensors

In [2]:
t = torch.tensor(4)

In [3]:
t

tensor(4)

In [4]:
torch.tensor([1,2,3,5,7,7])

tensor([1, 2, 3, 5, 7, 7])

In [6]:
n = [12,34,6,67,23]
n2 = np.array([1,2,3,4,4])
torch.tensor(n2)

tensor([1, 2, 3, 4, 4])

Arithimatic and Gredient

In [8]:
import torch as th

In [12]:
a = th.tensor(2)
b = th.tensor(3.,requires_grad=True)
c = th.tensor(4.0,requires_grad=True)

In [35]:
x = th.tensor(2.0,requires_grad=True)

In [40]:
y = th.tensor(4*x**2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


In [42]:
t = torch.full((5,5),17)

In [43]:
t

tensor([[17, 17, 17, 17, 17],
        [17, 17, 17, 17, 17],
        [17, 17, 17, 17, 17],
        [17, 17, 17, 17, 17],
        [17, 17, 17, 17, 17]])

In [44]:
torch.sin(t)

tensor([[-0.9614, -0.9614, -0.9614, -0.9614, -0.9614],
        [-0.9614, -0.9614, -0.9614, -0.9614, -0.9614],
        [-0.9614, -0.9614, -0.9614, -0.9614, -0.9614],
        [-0.9614, -0.9614, -0.9614, -0.9614, -0.9614],
        [-0.9614, -0.9614, -0.9614, -0.9614, -0.9614]])